### ISSUE TITLE
Cannot compare vs and vs-vs

### ISSUE THREAD

**Issue by afc163** [johnmpotter/npm-trends#13]
http://www.npmtrends.com/vs-vs-vs-vs

- http://npmjs.com/vs-vs
- http://npmjs.com/vs

**Comment by johnmpotter** [comment]
Thanks for letting me know! I initially thought that it was due to the way we use '-vs-' in the path to separate packages, but I think NPM doesn't have the download data for the vs-vs package quite yet. 

Here's the endpoint we load the download counts from: https://api.npmjs.org/downloads/range/2017-2-20:2017-08-17/vs-vs

**Comment by afc163** [comment]
Thx for response!

Here is my initial intention:

http://www.npmtrends.com/vs-vs-vs-vs-vs-vs

Will this url compare `vs` with `vs-vs-vs-vs`, or `vs-vs` with `vs-vs-vs`?
