### ISSUE TITLE
Show trends older than 2 years

### ISSUE THREAD

**Issue by andraaspar** [johnmpotter/npm-trends#59]
NPM is 10 years old, and if the API permits, it would be nice to see a bit further back in time. Maybe a 5 years option? Or maybe a ‘since the beginning’ option?

I guess it should be possible because https://npm-stat.com/ manages to pull it off.

**Comment by johnmpotter** [comment]
I had originally thought the API only allowed us to pull data up to 180 days. It turns out that each call can only return a 180 day window, but you can make calls for older windows. With that discovery, I just added the ability view the graph for "5 years" and "All time" (since the beginning). Although, as of now, "All time" is about 5 years as well since the data starts in 2015. Thanks for the suggestion!

**Comment by andraaspar** [comment]
Awesome! Thanks a lot!
